[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pycc"
version = "0.1.0"
description = "Python Compiler Collection"
readme = "README.md"
dependencies = [
  "pyparsing ~= 3.0"
]
